factor: 1.0
batch_size: 1024
ray_sample_mode: single_image  # [single_image, all_images]
data_at_gpu: true
bounds_factor: [ 0.5, 4.0 ]
# cam_list: ["FRONT", "FRONT_LEFT", "FRONT_RIGHT"]
cam_list: ["FRONT"]

load_lidar: false
load_depth: false

