factor: 1.0
ray_sample_mode: all_images
data_at_gpu: true
bounds_factor: [ 0.5, 2.0 ]
# cam_list: ["FRONT", "FRONT_LEFT", "FRONT_RIGHT"]
cam_list: ["FRONT", "FRONT_LEFT"]

load_lidar: false
load_depth: false

